spring.application.name=grillogic
spring.profiles.active=local

# Database
# Loads app-local.prop at app startup
spring.profiles.include=local
# Hibernate will auto-adjust database tables to match classes without wiping existing data
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.halt_on_error=true
# Prints every SQL query Hibernate generates to the console
spring.jpa.show-sql=true

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Thymeleaf
spring.thymeleaf.cache=false